//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace _192303M_IT2163_06_AppSec_Assignment
{


    public partial class _Default
    {

        /// <summary>
        /// lbl_msg control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lbl_msg;

        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new _192303M_IT2163_06_AppSec_Assignment.SiteMaster Master
        {
            get
            {
                return ((_192303M_IT2163_06_AppSec_Assignment.SiteMaster)(base.Master));
            }
        }
    }
}
